In [138]:
import pandas as pd

In [139]:
df = pd.read_csv('/Users/miriamg/Documents/GitHub_Ironhack/Week 3 SQL/Mini project/Clean_energy_countries.csv')

In [140]:
df.dropna(inplace=True)
df.reset_index(inplace=True)

In [141]:
df.rename(columns= {'Entity': 'Country', 'Renewable energy share in the total final energy consumption (%)': 're_share_in_total_ec_in_percentage'}, inplace= True)
df.columns

Index(['index', 'Unnamed: 0', 'Country', 'Year',
       'Access to electricity (% of population)',
       'Access to clean fuels for cooking',
       're_share_in_total_ec_in_percentage',
       'Electricity from fossil fuels (TWh)', 'Electricity from nuclear (TWh)',
       'Electricity from renewables (TWh)',
       'Low-carbon electricity (% electricity)',
       'Primary energy consumption per capita (kWh/person)',
       'Energy intensity level of primary energy (MJ/$2017 PPP GDP)', 'CO2',
       'gdp_growth', 'gdp_per_capita', 'Density', 'Land', 'Latitude',
       'Longitude'],
      dtype='object')

In [142]:
df.drop(columns= ['index', 'Unnamed: 0', 'Electricity from fossil fuels (TWh)', 'Electricity from nuclear (TWh)', 'Energy intensity level of primary energy (MJ/$2017 PPP GDP)', 'CO2', 'Density', 'Land', 'Latitude',
       'Longitude'], inplace= True)

df

,Country,Year,Access to electricity (% of population),Access to clean fuels for cooking,re_share_in_total_ec_in_percentage,Electricity from renewables (TWh),Low-carbon electricity (% electricity),Primary energy consumption per capita (kWh/person),gdp_growth,gdp_per_capita
0,Afghanistan,2000,1.613591,6.2,44.99,0.31,65.957440,302.59482,3.441610,13283.774348
1,Afghanistan,2001,4.074574,7.2,45.60,0.50,84.745766,236.89185,3.441610,13283.774348
2,Afghanistan,2002,9.409158,8.2,37.83,0.56,81.159424,210.86215,3.441610,179.426579
3,Afghanistan,2003,14.738506,9.5,36.66,0.63,67.021280,229.96822,8.832278,190.683814
4,Afghanistan,2004,20.064968,10.9,44.24,0.56,62.921350,204.23125,1.414118,211.382074
...,...,...,...,...,...,...,...,...,...,...
3592,Zimbabwe,2016,42.561730,29.8,81.90,3.32,48.680350,3227.68020,0.755869,1464.588957
3593,Zimbabwe,2017,44.178635,29.8,82.46,4.30,58.503407,3068.01150,4.709492,1235.189032
3594,Zimbabwe,2018,45.572647,29.9,80.23,5.46,59.412407,3441.98580,4.824211,1254.642265
3595,Zimbabwe,2019,46.781475,30.1,81.50,4.58,55.582527,3003.65530,-6.144236,1316.740657
3596,Zimbabwe,2020,52.747670,30.4,81.90,4.19,55.204216,2680.13180,-6.248748,1214.509820

In [143]:
df.rename(columns=lambda x: x.lower().replace("%", "").replace("(", "").replace(")", "").replace("/", "").replace("-", "").replace(" ", "_"), inplace=True)
df.columns

Index(['country', 'year', 'access_to_electricity__of_population',
       'access_to_clean_fuels_for_cooking',
       're_share_in_total_ec_in_percentage', 'electricity_from_renewables_twh',
       'lowcarbon_electricity__electricity',
       'primary_energy_consumption_per_capita_kwhperson', 'gdp_growth',
       'gdp_per_capita'],
      dtype='object')

In [157]:
df.rename(columns= {'access_to_electricity__of_population': 'population_access_to_electricity',
       'lowcarbon_electricity__electricity': 'lowcarbon_electricity'}, inplace= True)
df.columns

Index(['country', 'year', 'population_access_to_electricity',
       'access_to_clean_fuels_for_cooking',
       're_share_in_total_ec_in_percentage', 'electricity_from_renewables_twh',
       'lowcarbon_electricity',
       'primary_energy_consumption_per_capita_kwhperson', 'gdp_growth',
       'gdp_per_capita', 'country_id'],
      dtype='object')

In [158]:
countries = sorted(list(df['country'].unique()))
countries

['Afghanistan',
 'Albania',
 'Algeria',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bhutan',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cayman Islands',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czechia',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Grenada',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kuwait',
 'Kyrgyzstan',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Lithuania',
 'Luxembourg',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Macedonia',
 'Norway',
 'Oman',
 'Pakistan',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Romania',
 'Rwanda',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Tajikistan',
 'Thailand',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [159]:
country_id = list(range(1,len(countries)+1))
country_id

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173]

## Create country table

In [160]:
country_mapping = dict(zip(countries,country_id))
country_mapping

{'Afghanistan': 1,
 'Albania': 2,
 'Algeria': 3,
 'Angola': 4,
 'Antigua and Barbuda': 5,
 'Argentina': 6,
 'Armenia': 7,
 'Aruba': 8,
 'Australia': 9,
 'Austria': 10,
 'Azerbaijan': 11,
 'Bahamas': 12,
 'Bahrain': 13,
 'Bangladesh': 14,
 'Barbados': 15,
 'Belarus': 16,
 'Belgium': 17,
 'Belize': 18,
 'Benin': 19,
 'Bhutan': 20,
 'Bosnia and Herzegovina': 21,
 'Botswana': 22,
 'Brazil': 23,
 'Bulgaria': 24,
 'Burkina Faso': 25,
 'Burundi': 26,
 'Cambodia': 27,
 'Cameroon': 28,
 'Canada': 29,
 'Cayman Islands': 30,
 'Central African Republic': 31,
 'Chad': 32,
 'Chile': 33,
 'China': 34,
 'Colombia': 35,
 'Comoros': 36,
 'Congo': 37,
 'Costa Rica': 38,
 'Croatia': 39,
 'Cuba': 40,
 'Cyprus': 41,
 'Czechia': 42,
 'Denmark': 43,
 'Djibouti': 44,
 'Dominica': 45,
 'Dominican Republic': 46,
 'Ecuador': 47,
 'Egypt': 48,
 'El Salvador': 49,
 'Equatorial Guinea': 50,
 'Eritrea': 51,
 'Estonia': 52,
 'Eswatini': 53,
 'Ethiopia': 54,
 'Fiji': 55,
 'Finland': 56,
 'France': 57,
 'Gabon': 58,
 'Gambia': 59,
 'Georgia': 60,
 'Germany': 61,
 'Ghana': 62,
 'Greece': 63,
 'Grenada': 64,
 'Guatemala': 65,
 'Guinea': 66,
 'Guinea-Bissau': 67,
 'Guyana': 68,
 'Haiti': 69,
 'Honduras': 70,
 'Hungary': 71,
 'Iceland': 72,
 'India': 73,
 'Indonesia': 74,
 'Iraq': 75,
 'Ireland': 76,
 'Israel': 77,
 'Italy': 78,
 'Jamaica': 79,
 'Japan': 80,
 'Jordan': 81,
 'Kazakhstan': 82,
 'Kenya': 83,
 'Kiribati': 84,
 'Kuwait': 85,
 'Kyrgyzstan': 86,
 'Latvia': 87,
 'Lebanon': 88,
 'Lesotho': 89,
 'Liberia': 90,
 'Libya': 91,
 'Lithuania': 92,
 'Luxembourg': 93,
 'Madagascar': 94,
 'Malawi': 95,
 'Malaysia': 96,
 'Maldives': 97,
 'Mali': 98,
 'Malta': 99,
 'Mauritania': 100,
 'Mauritius': 101,
 'Mexico': 102,
 'Mongolia': 103,
 'Montenegro': 104,
 'Morocco': 105,
 'Mozambique': 106,
 'Myanmar': 107,
 'Namibia': 108,
 'Nauru': 109,
 'Nepal': 110,
 'Netherlands': 111,
 'New Caledonia': 112,
 'New Zealand': 113,
 'Nicaragua': 114,
 'Niger': 115,
 'Nigeria': 116,
 'North Macedonia': 117,
 'Norway': 118,
 'Oman': 119,
 'Pakistan': 120,
 'Panama': 121,
 'Papua New Guinea': 122,
 'Paraguay': 123,
 'Peru': 124,
 'Philippines': 125,
 'Poland': 126,
 'Portugal': 127,
 'Puerto Rico': 128,
 'Qatar': 129,
 'Romania': 130,
 'Rwanda': 131,
 'Saint Kitts and Nevis': 132,
 'Saint Lucia': 133,
 'Saint Vincent and the Grenadines': 134,
 'Samoa': 135,
 'Sao Tome and Principe': 136,
 'Saudi Arabia': 137,
 'Senegal': 138,
 'Serbia': 139,
 'Seychelles': 140,
 'Sierra Leone': 141,
 'Singapore': 142,
 'Slovakia': 143,
 'Slovenia': 144,
 'Solomon Islands': 145,
 'Somalia': 146,
 'South Africa': 147,
 'South Sudan': 148,
 'Spain': 149,
 'Sri Lanka': 150,
 'Sudan': 151,
 'Suriname': 152,
 'Sweden': 153,
 'Switzerland': 154,
 'Tajikistan': 155,
 'Thailand': 156,
 'Togo': 157,
 'Tonga': 158,
 'Trinidad and Tobago': 159,
 'Tunisia': 160,
 'Turkey': 161,
 'Turkmenistan': 162,
 'Uganda': 163,
 'Ukraine': 164,
 'United Arab Emirates': 165,
 'United Kingdom': 166,
 'United States': 167,
 'Uruguay': 168,
 'Uzbekistan': 169,
 'Vanuatu': 170,
 'Yemen': 171,
 'Zambia': 172,
 'Zimbabwe': 173}

In [161]:
df['country_id'] = df['country'].map(country_mapping)

In [162]:
df['country_id']

0         1
1         1
2         1
3         1
4         1
       ...
3592    173
3593    173
3594    173
3595    173
3596    173
Name: country_id, Length: 3597, dtype: int64

In [163]:
country_dict = {'country_id':country_id, 'country_name':countries}
country_df = pd.DataFrame(country_dict)
country_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   country_id    173 non-null    int64
 1   country_name  173 non-null    object
dtypes: int64(1), object(1)
memory usage: 2.8+ KB

In [167]:
country_df.to_csv("countries_renewables.csv")

## Create the indicators table

In [168]:
indicators_df = df[['year', 'population_access_to_electricity',
       'access_to_clean_fuels_for_cooking',
       're_share_in_total_ec_in_percentage', 'electricity_from_renewables_twh',
       'lowcarbon_electricity',
       'primary_energy_consumption_per_capita_kwhperson', 'gdp_growth',
       'gdp_per_capita', 'country_id']]

indicators_df = indicators_df.drop_duplicates()

In [169]:
indicators_df.columns

Index(['year', 'population_access_to_electricity',
       'access_to_clean_fuels_for_cooking',
       're_share_in_total_ec_in_percentage', 'electricity_from_renewables_twh',
       'lowcarbon_electricity',
       'primary_energy_consumption_per_capita_kwhperson', 'gdp_growth',
       'gdp_per_capita', 'country_id'],
      dtype='object')

## Create csv's

In [170]:
country_df.to_csv('country_table.csv')
indicators_df.to_csv('indicators_table.csv')